### ISSUE TITLE
Yi-hack with official application

### ISSUE THREAD

**Issue by alkhachatryan** [roleoroleo/yi-hack-MStar.gdrive#12]
Can I use the both of official application and yi-hack together?
I use yi-hack for gdrive storing and want to use the official yi-home for checking a live streaming.

How can I do it?

**Comment by alkhachatryan** [comment]
@roleoroleo

**Comment by alkhachatryan** [comment]
I got it.
So what I did is:

1. Do everything from yi-hack and yi-hack gdrive readme-s
2. Reset the camera
3. Scan the QR as you do usually
4. Pair with your camera
5. You now have both of applications

**Comment by roleoroleo** [comment]
If you don't disable cloud (from Configuration web page) the cam works both with the app and the hack.

**Comment by alkhachatryan** [comment]
Yes, @roleoroleo I go it. It works as sharm!
