### ISSUE TITLE
Limit google drive usage

### ISSUE THREAD

**Issue by alkhachatryan** [roleoroleo/yi-hack-MStar.gdrive#13]
I have 2 TB in google drive, but would like to limit the usage of camera, like to have 32GB for camera.
The camera will remove old videos from drive, if the space is full in gdrive, but how to set the limit in the configs? Delete old videos if X size used. 
I couldn't find anything.

**Comment by roleoroleo** [comment]
At the moment it's not possible. Sorry.

**Comment by alkhachatryan** [comment]
@roleoroleo can you tell me please which file is responsible for memory checking. I'll try to open a PR for that

**Comment by roleoroleo** [comment]
The logic is in the file GDriveUploader
But this code is not mine and I don't know it very well.

**Comment by denven** [comment]
> I have 2 TB in google drive, but would like to limit the usage of camera, like to have 32GB for camera. The camera will remove old videos from drive, if the space is full in gdrive, but how to set the limit in the configs? Delete old videos if X size used. I couldn't find anything.

I added this feature for the [OneDrive uploader](https://github.com/denven/yihack-onedrive-uploader) if you have a large space of one drive storage, you can have a try.
